// Interface content only. Stable IDs, not translated labels, are stored locally.
export const week7Spanish = {};
const pair = (en, es) => { week7Spanish[en] = es; return en; };
export const copy = {
  nav: pair('Final Integration', 'Integración final'),
  progress: pair('Weeks 1–7 of 7', 'Semanas 1–7 de 7'),
  eyebrow: pair('UNDERGRADUATE WEEK 7 · FINAL INTEGRATION + MANAGING AI', 'SEMANA 7 DE PREGRADO · INTEGRACIÓN FINAL Y GESTIÓN DE LA IA'),
  intro: pair('Bring together what you learned from planning, research, analysis, automation, and AI assistance. Decide where AI helps, where human judgment is necessary, and what should not be delegated to AI.', 'Integra lo aprendido sobre planificación, investigación, análisis, automatización y asistencia de IA. Decide dónde ayuda la IA, dónde se necesita el criterio humano y qué no debe delegarse a la IA.'),
  assessment: pair('Final AI Management Assessment', 'Evaluación final de gestión de IA'),
  purpose: pair('Apply your managerial judgment across the course. Choose one response per scenario, check your assessment, and revise any answer as often as needed.', 'Aplica tu criterio gerencial a lo aprendido en el curso. Elige una respuesta por escenario, comprueba tu evaluación y modifica cualquier respuesta tantas veces como necesites.'),
  submit: pair('Check Assessment', 'Comprobar evaluación'),
  incomplete: pair('Select one response for all eight questions before checking.', 'Selecciona una respuesta para cada una de las ocho preguntas antes de comprobar.'),
  correct: pair('Correct', 'Correcta'),
  incorrect: pair('Incorrect — review this decision', 'Incorrecta — revisa esta decisión'),
  result: pair('{0} of 8 management decisions aligned with the course principles.', '{0} de 8 decisiones de gestión se ajustaron a los principios del curso.'),
  demonstrated: pair('Demonstrated', 'Demostrado'),
  review: pair('Review recommended', 'Se recomienda repasar'),
  summary: pair('Capability summary', 'Resumen de capacidades'),
  pending: pair('Answers changed. Check again to update the latest submitted feedback and summary.', 'Las respuestas han cambiado. Comprueba de nuevo para actualizar los comentarios y el resumen de la última entrega.'),
  previous: pair('Feedback describes your latest submission.', 'Los comentarios corresponden a tu última entrega.'),
  submitted: pair('Submitted response', 'Respuesta entregada'),
  storage: pair('Week 7 work stays in this browser on this device. It does not sync; clearing site data removes it. Selections and drafts save automatically. You can return and revise your work.', 'El trabajo de la semana 7 permanece en este navegador y dispositivo. No se sincroniza; borrar los datos del sitio lo elimina. Las selecciones y los borradores se guardan automáticamente. Puedes volver y modificar tu trabajo.'),
  storageError: pair('Week 7 changes could not be saved. Check browser storage and try again.', 'No se pudieron guardar los cambios de la semana 7. Comprueba el almacenamiento del navegador e inténtalo de nuevo.'),
  readError: pair('Saved Week 7 data could not be read. It has not been overwritten. Restore browser storage access or recover the saved record before editing.', 'No se pudieron leer los datos guardados de la semana 7. No se han sobrescrito. Restablece el acceso al almacenamiento del navegador o recupera el registro guardado antes de editar.'),
  retry: pair('Retry saving Week 7', 'Volver a guardar la semana 7'),
  coastalIntro: pair('Act as the Operations Manager at Coastal Life. Use the supplied information and make your own decision under uncertainty.', 'Actúa como gerente de operaciones de Coastal Life. Usa la información proporcionada y toma tu propia decisión ante la incertidumbre.'),
  scenarioTitle: pair('Scenario and management information', 'Escenario e información de gestión'),
  scenario: pair('A guest at Oceanview Condo reports darker water staining on the bedroom ceiling. It is uncertain whether the area is currently wet.', 'Un huésped de Oceanview Condo informa de manchas de agua más oscuras en el techo del dormitorio. No se sabe si la zona está húmeda actualmente.'),
  routing: pair('The existing Guest Issue Response Workflow initially routes the issue as routine maintenance: no active leak, flooding, utilities loss, or immediate safety emergency is confirmed.', 'El flujo existente de respuesta a problemas de huéspedes deriva inicialmente el caso a mantenimiento rutinario: no se ha confirmado una fuga activa, inundación, pérdida de servicios básicos ni emergencia inmediata de seguridad.'),
  metrics: pair('Occupancy: 90% · Guest rating: 4.3 · Recent maintenance costs: $1,260 · Guest complaints: 7', 'Ocupación: 90% · Calificación de huéspedes: 4.3 · Costos recientes de mantenimiento: $1,260 · Quejas de huéspedes: 7'),
  limits: pair('These values may suggest a pattern requiring management attention, but they do not establish the cause of the current ceiling staining.', 'Estos valores pueden sugerir un patrón que requiere atención gerencial, pero no establecen la causa de las manchas actuales del techo.'),
  prior: pair('A prior note says previous discoloration was inspected and no active leak was found at that time. That observation does not establish the current condition or cause.', 'Una nota anterior indica que se inspeccionó una decoloración previa y no se encontró una fuga activa en ese momento. Esa observación no establece la condición ni la causa actuales.'),
  workflow: pair('The workflow can organize, document, and route the issue; a manager can intervene.', 'El flujo puede organizar, documentar y derivar el problema; un gerente puede intervenir.'),
  grace: pair('Grace can provide approved information about responsibilities, procedures, authority, and when human involvement is required. Grace cannot inspect the property, establish the physical cause of the staining, or own the management decision.', 'Grace puede proporcionar información aprobada sobre responsabilidades, procedimientos, autoridad y cuándo se requiere intervención humana. Grace no puede inspeccionar la propiedad, establecer la causa física de las manchas ni asumir la decisión de gestión.'),
  question: pair('Is there an active water or moisture problem now?', '¿Hay un problema activo de agua o humedad ahora?'),
  situation: pair('1. Management Situation Assessment', '1. Evaluación de la situación de gestión'),
  classify: pair('Classify each statement using the supplied information.', 'Clasifica cada afirmación usando la información proporcionada.'),
  information: pair('2. Information & AI Review', '2. Revisión de información e IA'),
  informationHelp: pair('Choose how you would use each source or capability in this case. No previous workspace records are copied here.', 'Elige cómo usarías cada fuente o capacidad en este caso. Aquí no se copian registros anteriores del espacio de trabajo.'),
  human: pair('3. Human-Control Decision', '3. Decisión de control humano'),
  humanLabel: pair('Where will you apply human control?', '¿Dónde aplicarás el control humano?'),
  justification: pair('Briefly justify your intervention or review point', 'Justifica brevemente tu intervención o punto de revisión'),
  final: pair('4. Final Management Decision & Accountability', '4. Decisión final de gestión y responsabilidad'),
  action: pair('Your final management decision / next action', 'Tu decisión final de gestión / próxima acción'),
  reason: pair('Brief reason, including uncertainty or verification needed', 'Razón breve, incluida la incertidumbre o verificación necesaria'),
  accountable: pair('Who remains accountable for the management decision?', '¿Quién sigue siendo responsable de la decisión de gestión?'),
  choose: pair('Choose a response', 'Elige una respuesta'),
  short: pair('Keep each written response to one or two sentences (maximum 400 characters).', 'Limita cada respuesta escrita a una o dos frases (máximo 400 caracteres).'),
  principle: pair('An integrated AI-enabled system can organize information, identify patterns, apply established processes, and provide approved information, but responsibility for the management decision remains human.', 'Un sistema integrado con IA puede organizar información, identificar patrones, aplicar procesos establecidos y proporcionar información aprobada, pero la responsabilidad de la decisión de gestión sigue siendo humana.'),
  save: pair('Save completed Coastal Life work', 'Guardar trabajo completado de Coastal Life'),
  saved: pair('Coastal Life work saved. All responses remain editable.', 'Trabajo de Coastal Life guardado. Todas las respuestas siguen siendo editables.'),
  draft: pair('Coastal Life draft saved. Complete all fields to record your finished work.', 'Borrador de Coastal Life guardado. Completa todos los campos para registrar tu trabajo terminado.'),
  required: pair('Complete each selection and short response before saving completed work.', 'Completa cada selección y respuesta breve antes de guardar el trabajo terminado.'),
};
export const capabilities = [
  pair('Planning & Approval', 'Planificación y aprobación'),
  pair('Research & Verification', 'Investigación y verificación'),
  pair('Analysis & Evidence', 'Análisis y evidencia'),
  pair('Automation & Human Control', 'Automatización y control humano'),
  pair('AI Assistant Boundaries', 'Límites del asistente de IA'),
];
const q = (id, capability, prompt, options, correct, explanation) => ({ id, capability, prompt: pair(...prompt), options: options.map(p => pair(...p)), correct, explanation: pair(...explanation) });
export const questions = [
  q('research', 1, ['AI recommends a supplier using a claim whose original source has not been checked. What should you do?', 'La IA recomienda un proveedor usando una afirmación cuya fuente original no se ha comprobado. ¿Qué debes hacer?'], [
    ['Use the claim because the recommendation is detailed.', 'Usar la afirmación porque la recomendación es detallada.'], ['Verify the claim and original source before relying on it.', 'Verificar la afirmación y la fuente original antes de basarse en ella.'], ['Ask AI to repeat the claim more confidently.', 'Pedir a la IA que repita la afirmación con más seguridad.'], ['Treat agreement between AI responses as source verification.', 'Tratar la coincidencia entre respuestas de IA como verificación de la fuente.'],
  ], 1, ['A plausible claim is not verified evidence. Check the original source and whether it supports the recommendation.', 'Una afirmación plausible no es evidencia verificada. Comprueba la fuente original y si respalda la recomendación.']),
  q('exception', 3, ['An automated workflow encounters a case outside its defined conditions. What is the best response?', 'Un flujo automatizado encuentra un caso fuera de sus condiciones definidas. ¿Cuál es la mejor respuesta?'], [
    ['Let it create a new rule for this case.', 'Permitir que cree una regla nueva para este caso.'], ['Force the case into the nearest existing category.', 'Forzar el caso a la categoría existente más cercana.'], ['Ignore the exception until the next reporting cycle.', 'Ignorar la excepción hasta el próximo ciclo de informes.'], ['Escalate the exception for appropriate human review.', 'Derivar la excepción para la revisión humana adecuada.'],
  ], 3, ['Automation must remain within approved rules. Exceptions need human review rather than invented rules.', 'La automatización debe mantenerse dentro de las reglas aprobadas. Las excepciones necesitan revisión humana, no reglas inventadas.']),
  q('cause', 2, ['AI finds that complaints and maintenance costs increased together and says one caused the other. What should you conclude?', 'La IA detecta que las quejas y los costos de mantenimiento aumentaron juntos y afirma que uno causó el otro. ¿Qué debes concluir?'], [
    ['The causal explanation needs additional evidence.', 'La explicación causal necesita evidencia adicional.'], ['The pattern proves the stated cause.', 'El patrón demuestra la causa indicada.'], ['A clear chart removes the need to investigate.', 'Un gráfico claro elimina la necesidad de investigar.'], ['The larger number must be the cause.', 'La cifra mayor debe ser la causa.'],
  ], 0, ['A pattern can guide investigation, but association alone does not establish cause.', 'Un patrón puede orientar la investigación, pero la asociación por sí sola no establece causalidad.']),
  q('boundary', 4, ['A bounded AI assistant cannot find an answer in its approved information. How should it respond?', 'Un asistente de IA con límites definidos no encuentra una respuesta en su información aprobada. ¿Cómo debe responder?'], [
    ['Invent a likely answer to avoid delay.', 'Inventar una respuesta probable para evitar demoras.'], ['Present general knowledge as company policy.', 'Presentar conocimientos generales como política de la empresa.'], ['Acknowledge the limitation and refer to an authorized person or source.', 'Reconocer la limitación y remitir a una persona o fuente autorizada.'], ['Make the decision on the manager’s behalf.', 'Tomar la decisión en nombre del gerente.'],
  ], 2, ['A bounded assistant must stay within approved knowledge and authority, and acknowledge when human help is needed.', 'Un asistente con límites definidos debe respetar el conocimiento y la autoridad aprobados y reconocer cuándo se necesita ayuda humana.']),
  q('planning', 0, ['AI proposes moving an important deadline to balance workload. What should the manager do?', 'La IA propone mover un plazo importante para equilibrar la carga de trabajo. ¿Qué debe hacer el gerente?'], [
    ['Accept the change because the workload is balanced.', 'Aceptar el cambio porque la carga está equilibrada.'], ['Review priorities and authority, then approve or revise the proposal.', 'Revisar las prioridades y la autoridad y luego aprobar o modificar la propuesta.'], ['Let AI notify everyone that the deadline has changed.', 'Permitir que la IA avise a todos que el plazo ha cambiado.'], ['Remove human approval from future plans.', 'Eliminar la aprobación humana de los planes futuros.'],
  ], 1, ['AI can propose plans. Humans remain responsible for priorities, authorized changes, and approval.', 'La IA puede proponer planes. Las personas siguen siendo responsables de las prioridades, los cambios autorizados y la aprobación.']),
  q('rules', 3, ['A team wants to automate routine issue routing. Which approach is appropriate?', 'Un equipo quiere automatizar la derivación de problemas rutinarios. ¿Qué enfoque es adecuado?'], [
    ['Use defined conditions, approved routes, and an exception review process.', 'Usar condiciones definidas, rutas aprobadas y un proceso de revisión de excepciones.'], ['Allow the automation to expand its authority when busy.', 'Permitir que la automatización amplíe su autoridad cuando haya mucho trabajo.'], ['Route every issue without monitoring or review.', 'Derivar todos los problemas sin supervisión ni revisión.'], ['Treat an automated route as proof the issue is resolved.', 'Tratar una derivación automática como prueba de que el problema está resuelto.'],
  ], 0, ['Deterministic automation is useful for defined rules with controls and escalation; routing does not prove resolution.', 'La automatización determinista sirve para reglas definidas con controles y escalamiento; derivar no demuestra que se haya resuelto el problema.']),
  q('uncertainty', 2, ['AI recommends a consequential action, but current evidence is incomplete and approval authority is unclear. What next?', 'La IA recomienda una acción de consecuencias importantes, pero la evidencia actual es incompleta y la autoridad de aprobación no está clara. ¿Qué sigue?'], [
    ['Proceed because AI supplied a recommendation.', 'Proceder porque la IA proporcionó una recomendación.'], ['Assume missing evidence supports the recommendation.', 'Suponer que la evidencia faltante respalda la recomendación.'], ['Delegate approval to the automated system.', 'Delegar la aprobación al sistema automatizado.'], ['Seek current evidence and authorized human review before committing.', 'Buscar evidencia actual y revisión humana autorizada antes de comprometerse.'],
  ], 3, ['Incomplete evidence and uncertain authority require human judgment and verification, especially when consequences are significant.', 'La evidencia incompleta y la autoridad incierta requieren criterio humano y verificación, especialmente cuando las consecuencias son importantes.']),
  q('accountability', 0, ['A manager approves an AI-supported decision that later causes problems. Who is responsible for the management decision?', 'Un gerente aprueba una decisión apoyada por IA que después causa problemas. ¿Quién es responsable de la decisión de gestión?'], [
    ['Only the assistant that drafted the recommendation.', 'Solo el asistente que redactó la recomendación.'], ['No one, because several systems contributed.', 'Nadie, porque contribuyeron varios sistemas.'], ['The human manager remains accountable for the approved decision.', 'El gerente humano sigue siendo responsable de la decisión aprobada.'], ['Only the automated workflow that recorded it.', 'Solo el flujo automatizado que la registró.'],
  ], 2, ['AI support does not transfer managerial accountability. Humans must evaluate, approve, and own their decisions.', 'El apoyo de IA no transfiere la responsabilidad gerencial. Las personas deben evaluar, aprobar y asumir sus decisiones.']),
];
const option = (id, en, es) => ({ id, label: pair(en, es) });
export const classifications = [option('known', 'Known from the supplied report', 'Conocido por el informe proporcionado'), option('unknown', 'Not established by the supplied information', 'No establecido por la información proporcionada'), option('can', 'Within the system’s capabilities', 'Dentro de las capacidades del sistema'), option('cannot', 'Beyond the system’s capabilities', 'Fuera de las capacidades del sistema')];
export const statements = [
  option('stain', 'The guest reports darker ceiling staining.', 'El huésped informa de manchas más oscuras en el techo.'),
  option('moisture', 'There is active moisture now.', 'Hay humedad activa ahora.'),
  option('route', 'The workflow can document and route the issue.', 'El flujo puede documentar y derivar el problema.'),
  option('diagnose', 'Grace can determine the physical cause remotely.', 'Grace puede determinar la causa física a distancia.'),
];
export const reviews = [
  { id: 'researchReview', label: pair('Research & Verification — prior inspection note', 'Investigación y verificación — nota de inspección anterior'), options: [option('verify', 'Useful context; verify current conditions separately.', 'Contexto útil; verificar las condiciones actuales por separado.'), option('conclusive', 'Conclusive evidence of the current condition.', 'Evidencia concluyente de la condición actual.')] },
  { id: 'analysisReview', label: pair('Data Analysis & Decision Support — property metrics', 'Análisis de datos y apoyo a las decisiones — métricas de la propiedad'), options: [option('cause', 'The metrics establish the cause of this staining.', 'Las métricas establecen la causa de estas manchas.'), option('pattern', 'Useful pattern for attention; not proof of this cause.', 'Patrón útil para orientar la atención; no prueba esta causa.')] },
  { id: 'workflowReview', label: pair('Workflow & Automation — routine routing', 'Flujo de trabajo y automatización — derivación rutinaria'), options: [option('route', 'Organizes and routes; a manager may intervene.', 'Organiza y deriva; un gerente puede intervenir.'), option('resolved', 'Establishes that the current issue is resolved.', 'Establece que el problema actual está resuelto.')] },
  { id: 'graceReview', label: pair('Grace — approved information', 'Grace — información aprobada'), options: [option('decision', 'Can inspect the condition and own the decision.', 'Puede inspeccionar la condición y asumir la decisión.'), option('bounded', 'Can explain approved procedures and authority, not diagnose the property.', 'Puede explicar procedimientos y autoridad aprobados, no diagnosticar la propiedad.')] },
];
export const interventions = [option('verify', 'Arrange human verification of current conditions.', 'Organizar la verificación humana de las condiciones actuales.'), option('escalate', 'Escalate for authorized management review.', 'Derivar para revisión gerencial autorizada.'), option('monitor', 'Retain routine routing with a defined human follow-up point.', 'Mantener la derivación rutinaria con un punto definido de seguimiento humano.'), option('other', 'Another human-control approach (explain below).', 'Otro enfoque de control humano (explica abajo).')];
export const owners = [option('manager', 'I remain accountable as the Operations Manager.', 'Sigo siendo responsable como gerente de operaciones.'), option('authorized', 'An authorized human manager remains accountable; I will arrange the handoff.', 'Un gerente humano autorizado sigue siendo responsable; organizaré el traspaso.')];
