// Interface-only translations. Stored values, source documents and student text stay unchanged.
import { week7Spanish } from './finalIntegrationContent.js';
export const spanish = {
  ...week7Spanish,
  "Mark {0} complete": "Marcar {0} como completada",
  "Mark {0} incomplete": "Marcar {0} como pendiente",
  "Which properties need the most management attention, and what should Coastal Life prioritize to improve performance?": "¿Qué propiedades requieren más atención de la gerencia y qué debería priorizar Coastal Life para mejorar el desempeño?",
  "early": "de anticipación",
  "late": "de retraso",
  "today": "hoy",
  "tomorrow": "mañana",
  "complete": "completada",
  "incomplete": "pendiente",
  "approved": "aprobada",
  "rejected": "rechazada",
  "Missing task {0}": "Tarea no encontrada {0}",
  "No work scheduled.": "No hay trabajo programado.",
  "Dashboard checks — rules, not AI": "Comprobaciones del panel: reglas, no IA",
  "Today:": "Hoy:",
  "Tomorrow:": "Mañana:",
  "Uses each task’s full remaining estimate, excluding completed tasks. This compares time totals, not personal feasibility. No task splitting or hidden rescheduling.": "Utiliza la estimación completa restante de cada tarea y excluye las completadas. Compara totales de tiempo, no la viabilidad personal. No divide tareas ni las reprograma de forma oculta.",
  "No dependency-order or deadline conflicts detected in this sequence. Still review the assumptions.": "No se detectaron conflictos de requisitos previos ni de fechas en esta secuencia. Revisa también los supuestos.",
  "Available time must be blank (unknown) or between 0 and 24 hours per day.": "El tiempo disponible debe quedar en blanco (desconocido) o ser de 0 a 24 horas por día.",
  "Select at least one unfinished task for the planning prompt.": "Selecciona al menos una tarea pendiente para la instrucción de planificación.",
  "Planning prompt prepared. Copy it to your approved AI tool.": "Instrucción de planificación preparada. Cópiala en tu herramienta de IA aprobada.",
  "Prepare a planning prompt first so task ids and context can be checked.": "Prepara primero una instrucción de planificación para comprobar los identificadores y el contexto.",
  "AI recommendation imported for review. Your task details have not changed.": "Recomendación de IA importada para revisión. Los datos de tus tareas no han cambiado.",
  "Explain your decision: what did you accept or change, and why?": "Explica tu decisión: ¿qué aceptaste o cambiaste y por qué?",
  "Confirm that you reviewed the recommendation, assumptions, and dashboard checks.": "Confirma que revisaste la recomendación, los supuestos y las comprobaciones del panel.",
  "Include at least one task, or reject the recommendation.": "Incluye al menos una tarea o rechaza la recomendación.",
  "Your accepted plan and explanation are saved locally.": "Tu plan aceptado y tu explicación se guardaron localmente.",
  "Your rejection and explanation are saved locally.": "Tu rechazo y tu explicación se guardaron localmente.",
  "Prepare AI Planning Prompt": "Preparar instrucción de planificación para IA",
  "AI proposes → dashboard checks → student evaluates → student decides.": "La IA propone → el panel comprueba → el estudiante evalúa → el estudiante decide.",
  "Select tasks to include": "Seleccionar tareas para incluir",
  "Prerequisites are included automatically with their completion status. Review the generated prompt before sharing.": "Los requisitos previos se incluyen automáticamente con su estado de finalización. Revisa la instrucción antes de compartirla.",
  "Select unfinished tasks": "Seleccionar tareas pendientes",
  "Include": "Incluir",
  "Add an unfinished task first.": "Primero añade una tarea pendiente.",
  "tasks including prerequisites in this selection.": "tareas, incluidos los requisitos previos, en esta selección.",
  "Available hours today": "Horas disponibles hoy",
  "Available hours tomorrow": "Horas disponibles mañana",
  "Leave blank if unknown; zero means no available time. Availability belongs to today’s date and is not carried forward automatically.": "Deja el campo en blanco si no lo sabes; cero significa que no hay tiempo disponible. La disponibilidad corresponde a hoy y no se traslada automáticamente a otro día.",
  "Available time saved for today and tomorrow.": "Tiempo disponible guardado para hoy y mañana.",
  "Save available time": "Guardar tiempo disponible",
  "Generate planning prompt": "Generar instrucción de planificación",
  "Preparing a new prompt starts a new review and replaces the previous recommendation/decision record. Existing tasks are never replaced.": "Preparar una nueva instrucción inicia otra revisión y sustituye la recomendación y decisión anteriores. Las tareas existentes nunca se sustituyen.",
  "Planning prompt": "Instrucción de planificación",
  "Needs review.": "Requiere revisión.",
  "Tasks, available time, or the planning date changed since this prompt was prepared. Compare current facts below or prepare a fresh prompt.": "Las tareas, el tiempo disponible o la fecha cambiaron desde que se preparó esta instrucción. Compara los datos actuales o prepara una nueva.",
  "AI planning response": "Respuesta de planificación de IA",
  "Paste the complete JSON recommendation from your approved AI tool.": "Pega la recomendación JSON completa de tu herramienta de IA aprobada.",
  "Review AI recommendation": "Revisar recomendación de IA",
  "AI recommendation": "Recomendación de IA",
  "AI suggestion · not approved": "Sugerencia de IA · sin aprobar",
  "Original proposed order and explanation, preserved for comparison.": "Orden y explicación originales propuestos, conservados para comparar.",
  "Assumptions to check": "Supuestos por comprobar",
  "No assumptions supplied. Check for unstated assumptions.": "No se proporcionaron supuestos. Comprueba si hay supuestos implícitos.",
  "Work not scheduled by AI": "Trabajo no programado por la IA",
  "All selected unfinished work was included.": "Se incluyó todo el trabajo pendiente seleccionado.",
  "Student decision": "Decisión del estudiante",
  "Your judgment": "Tu criterio",
  "Review your plan": "Revisa tu plan",
  "Reorder, change the planned day or reason, and exclude work. These edits do not change task fields. Draft edits are saved only when you save your decision.": "Cambia el orden, el día o el motivo, o excluye tareas. Estos cambios no modifican los campos de las tareas. El borrador se guarda solo al guardar tu decisión.",
  "Missing task": "Tarea no encontrada",
  "Planned day for step": "Día previsto para el paso",
  "Today": "Hoy",
  "Tomorrow": "Mañana",
  "Your reason for step": "Tu motivo para el paso",
  "Move step": "Mover paso",
  "up": "hacia arriba",
  "down": "hacia abajo",
  "Exclude step": "Excluir paso",
  "Outside your draft plan": "Fuera del borrador de tu plan",
  "Added by student; explain this choice.": "Añadido por el estudiante; explica esta elección.",
  "in plan": "en el plan",
  "My decision and explanation": "Mi decisión y explicación",
  "What did you accept, change, or reject, and why?": "¿Qué aceptaste, cambiaste o rechazaste y por qué?",
  "I reviewed the assumptions, capacity, dependencies, and any Needs review notice. I take responsibility for this decision.": "Revisé los supuestos, la capacidad, las dependencias y los avisos de revisión. Asumo la responsabilidad de esta decisión.",
  "Save accepted plan": "Guardar plan aceptado",
  "Reject recommendation": "Rechazar recomendación",
  "Saved student decision": "Decisión guardada del estudiante",
  "Student-approved plan": "Plan aprobado por el estudiante",
  "Student rejected recommendation": "El estudiante rechazó la recomendación",
  "Saved": "Guardado",
  "Needs review against changed facts.": "Requiere revisión frente a los datos modificados.",
  "This is your saved decision; drafts above do not change it until saved.": "Esta es tu decisión guardada; los borradores anteriores no la modifican hasta guardarlos.",
  "Paste task information before preparing the prompt.": "Pega información de tareas antes de preparar la instrucción.",
  "New prompt prepared. Copy it to your approved AI tool, then return here with the response.": "Nueva instrucción preparada. Cópiala en tu herramienta de IA aprobada y vuelve con la respuesta.",
  "Proposed Tasks are ready for review. No tasks have been added to the Planner.": "Las tareas propuestas están listas para revisar. No se ha añadido ninguna al Planificador.",
  "Reviewed task added to Planner.": "Tarea revisada añadida al Planificador.",
  "Approved: {0}": "Aprobada: {0}",
  "Ready for a new task import. Your saved Planner tasks were kept.": "Todo listo para una nueva importación. Se conservaron tus tareas guardadas.",
  "Prepare AI Task Import": "Preparar importación de tareas con IA",
  "Turn syllabus, course schedule, instructor-list, workplace, or spreadsheet-style text into proposals using an external AI tool. Review the result here before adding anything to Planner.": "Convierte texto del programa, calendario, lista del docente, trabajo u hoja de cálculo en propuestas mediante una herramienta de IA externa. Revisa el resultado antes de añadirlo al Planificador.",
  "Task information": "Información de tareas",
  "Paste the relevant academic or workplace task information here. Remove sensitive information first.": "Pega aquí la información académica o laboral pertinente. Elimina primero la información sensible.",
  "Generate task-import prompt": "Generar instrucción de importación",
  "Task-import prompt": "Instrucción de importación de tareas",
  "AI task response": "Respuesta de tareas de IA",
  "Paste the complete JSON response from your AI tool. You do not need to write code.": "Pega la respuesta JSON completa de tu herramienta de IA. No necesitas escribir código.",
  "Parsing checks the response format; it is not AI. Task-import source, prompt, AI response, and unapproved proposals are temporary. Refreshing the page or starting a new task import clears them. Approved Planner tasks remain saved.": "El análisis de formato comprueba la respuesta; no es IA. La fuente, la instrucción, la respuesta y las propuestas sin aprobar son temporales. Actualizar la página o iniciar otra importación las elimina. Las tareas aprobadas permanecen guardadas.",
  "Review proposed tasks": "Revisar tareas propuestas",
  "Start new task import": "Iniciar nueva importación",
  "Proposed Tasks": "Tareas propuestas",
  "Check dates, effort, priority, sources, and prerequisites. Approve prerequisites first. Each approval adds one task; rejecting a proposal does not delete a saved task.": "Comprueba fechas, esfuerzo, prioridad, fuentes y requisitos previos. Aprueba primero los requisitos previos. Cada aprobación añade una tarea; rechazar una propuesta no elimina tareas guardadas.",
  "Proposal {0}": "Propuesta {0}",
  "Untitled proposal": "Propuesta sin título",
  "Source excerpt:": "Extracto de la fuente:",
  "Not supplied": "No proporcionado",
  "Proposed title": "Título propuesto",
  "Proposed category": "Categoría propuesta",
  "Proposed due date": "Fecha de entrega propuesta",
  "Proposed hours": "Horas propuestas",
  "Proposed priority": "Prioridad propuesta",
  "Choose priority": "Elegir prioridad",
  "High": "Alta",
  "Medium": "Media",
  "Low": "Baja",
  "Proposed notes": "Notas propuestas",
  "I checked this proposal against the source and reviewed every flag.": "Comprobé esta propuesta con la fuente y revisé todos los avisos.",
  "Approve task": "Aprobar tarea",
  "Rejected proposal {0}. No task was saved.": "Propuesta {0} rechazada. No se guardó ninguna tarea.",
  "Reject task": "Rechazar tarea",
  "Approved proposal. Manage the saved task in Your tasks.": "Propuesta aprobada. Gestiona la tarea guardada en Tus tareas.",
  "Rejected proposal. Nothing was added to Planner.": "Propuesta rechazada. No se añadió nada al Planificador.",
  "Invalid CSV quoting. Put double quotes around the complete field.": "Comillas CSV no válidas. Encierra el campo completo entre comillas dobles.",
  "A quoted field is missing its closing double quote.": "Falta la comilla doble de cierre de un campo.",
  "Enter column headings and at least one data record.": "Introduce encabezados de columnas y al menos un registro de datos.",
  "Each column needs a unique, nonempty heading.": "Cada columna necesita un encabezado único y no vacío.",
  "Record {0} has {1} fields; expected {2}. Quote values containing commas.": "El registro {0} tiene {1} campos; se esperaban {2}. Usa comillas en valores que contengan comas.",
  "Paste the structured JSON response requested by the prompt, then import again.": "Pega la respuesta JSON estructurada solicitada y vuelve a importarla.",
  "The response must contain a nonempty findings array.": "La respuesta debe contener una lista findings no vacía.",
  "Yes": "Sí",
  "No": "No",
  "Finding {0} needs finding, evidence, meaning, Needs More Information (Yes/No), and additional information when Yes. No proposals were imported.": "El hallazgo {0} necesita finding, evidence, meaning, Needs More Information (Yes/No) e información adicional cuando sea Yes. No se importaron propuestas.",
  "Saved Analysis data could not be read. It has not been overwritten. Restore browser storage access or recover the data, then reload.": "No se pudieron leer los datos de Análisis guardados. No se sobrescribieron. Restablece el acceso al almacenamiento o recupera los datos y recarga la página.",
  "What needs the most management attention?": "¿Qué requiere más atención de la gerencia?",
  "Evidence Supporting Your Decision": "Evidencia que respalda tu decisión",
  "Recommended Management Action": "Acción de gestión recomendada",
  "What information would you want before acting?": "¿Qué información querrías antes de actuar?",
  "Analysis changes could not be saved. Check browser storage or available space and try again.": "No se pudieron guardar los cambios de Análisis. Comprueba el almacenamiento o espacio disponible e inténtalo de nuevo.",
  "Dataset loaded and saved in this browser.": "Conjunto de datos cargado y guardado en este navegador.",
  "{0} The previously loaded dataset, if any, remains unchanged.": "{0} El conjunto de datos cargado anteriormente, si lo había, no ha cambiado.",
  "Complete the finding, evidence, meaning, and any requested additional information.": "Completa el hallazgo, la evidencia, el significado y la información adicional solicitada.",
  "Analysis Record saved.": "Registro de análisis guardado.",
  "Affirm the responsibility acknowledgment before saving your Management Decision.": "Confirma que asumes la responsabilidad antes de guardar tu decisión de gestión.",
  "Complete all four Management Decision responses.": "Completa las cuatro respuestas de la decisión de gestión.",
  "Management Decision saved in this browser.": "Decisión de gestión guardada en este navegador.",
  "Management Decision could not be saved. Check browser storage or available space and try again.": "No se pudo guardar la decisión de gestión. Comprueba el almacenamiento o espacio disponible e inténtalo de nuevo.",
  "Week 4 · DATA → ANALYZE → REVIEW → DECIDE": "Semana 4 · DATOS → ANALIZAR → REVISAR → DECIDIR",
  "Data Analysis & Decision Support": "Análisis de datos y apoyo a las decisiones",
  "Use data and AI-supported analysis to identify patterns, evaluate evidence, and make an informed decision.": "Utiliza datos y análisis con apoyo de IA para identificar patrones, evaluar evidencia y tomar una decisión informada.",
  "AI can assist with analysis. You are responsible for checking the analysis and making the decision.": "La IA puede ayudar con el análisis. Tú eres responsable de comprobarlo y tomar la decisión.",
  "Start with your completion history below. Generate an AI prompt, check the response against your data, and save your judgment.": "Empieza con tu historial de finalización. Genera una instrucción para IA, contrasta la respuesta con tus datos y guarda tu criterio.",
  "Practice the same analysis process with Coastal Life property data. Open the supplied exercise, copy the CSV into Dataset Input, and load it before preparing your AI prompt.": "Practica el mismo proceso con los datos de propiedades de Coastal Life. Abre el ejercicio, copia el CSV en Entrada de datos y cárgalo antes de preparar la instrucción para IA.",
  "Supplied Coastal Life exercise": "Ejercicio proporcionado de Coastal Life",
  "Supplied dataset (CSV)": "Conjunto de datos proporcionado (CSV)",
  "Supplied dataset copied. Paste it into Dataset Input.": "Datos copiados. Pégalos en Entrada de datos.",
  "Copy was unavailable. Select the supplied CSV and copy it manually.": "No se pudo copiar. Selecciona el CSV proporcionado y cópialo manualmente.",
  "Copy supplied dataset": "Copiar datos proporcionados",
  "Use Coastal Life as the Dataset Name and the question above as your Management Question. Copying does not replace your saved dataset.": "Usa Coastal Life como nombre del conjunto de datos y la pregunta anterior como pregunta de gestión. Copiar no sustituye tus datos guardados.",
  "Data — Dataset Workspace": "Datos — Espacio de trabajo con datos",
  "Dataset Name": "Nombre del conjunto de datos",
  "Management Question": "Pregunta de gestión",
  "Dataset Input": "Entrada de datos",
  "Paste CSV with unique column headings followed by records. Quote fields containing commas. Loading replaces the dataset; existing findings and decisions remain for you to review against the new data.": "Pega un CSV con encabezados únicos seguidos de registros. Usa comillas en campos con comas. Cargar sustituye los datos; los hallazgos y decisiones permanecen para revisarlos frente a los nuevos datos.",
  "Load Dataset": "Cargar datos",
  "Loaded dataset": "Datos cargados",
  "records ·": "registros ·",
  "columns. Input edits take effect when you load the dataset.": "columnas. Los cambios de entrada se aplican al cargar los datos.",
  "Select a column heading to sort ascending; select it again to sort descending.": "Selecciona un encabezado para ordenar de forma ascendente; selecciónalo otra vez para ordenar de forma descendente.",
  "Loaded dataset table": "Tabla de datos cargados",
  "Numeric summaries": "Resúmenes numéricos",
  "Plain numeric columns only. Count excludes blank cells; averages display up to four decimal places.": "Solo columnas numéricas simples. El recuento excluye celdas vacías; los promedios muestran hasta cuatro decimales.",
  "Count": "Recuento",
  "Average": "Promedio",
  "Minimum": "Mínimo",
  "Maximum": "Máximo",
  "No numeric columns recognized.": "No se reconocieron columnas numéricas.",
  "Analyze — Prepare External AI Analysis": "Analizar — Preparar análisis con IA externa",
  "Copy the prompt into a course-approved external AI tool. This dashboard makes no AI/API requests.": "Copia la instrucción en una herramienta de IA externa aprobada para el curso. Este panel no realiza solicitudes de IA/API.",
  "Load a dataset and enter a Dataset Name and Management Question before preparing a prompt.": "Carga datos e introduce un nombre y una pregunta de gestión antes de preparar la instrucción.",
  "Prepare AI Analysis Prompt": "Preparar instrucción de análisis para IA",
  "AI Analysis Prompt": "Instrucción de análisis para IA",
  "Prompt copied.": "Instrucción copiada.",
  "Copy was unavailable. Select the prompt text and copy it manually.": "No se pudo copiar. Selecciona la instrucción y cópiala manualmente.",
  "Copy prompt": "Copiar instrucción",
  "Paste AI Analysis": "Pegar análisis de IA",
  "Review the AI analysis against the actual dataset. Record only findings you believe the evidence supports. Pasting a response does not create accepted Analysis Records.": "Contrasta el análisis de IA con los datos reales. Registra solo los hallazgos que consideres respaldados. Pegar una respuesta no crea registros de análisis aceptados.",
  "{0} AI-proposed drafts imported for review. None are accepted yet.": "Se importaron {0} borradores de IA para revisión. Aún no se ha aceptado ninguno.",
  "Import proposed findings": "Importar hallazgos propuestos",
  "Paste the JSON findings requested by the prompt. Review or reject all current proposals before importing another response. Draft proposals are temporary and are not saved on navigation or refresh.": "Pega los hallazgos JSON solicitados. Revisa o rechaza todas las propuestas antes de importar otra respuesta. Los borradores son temporales y no se guardan al navegar o actualizar.",
  "AI-proposed finding {0}": "Hallazgo propuesto por IA {0}",
  "Complete the proposed finding, evidence, meaning, and additional information when Yes before accepting.": "Completa el hallazgo, evidencia, significado e información adicional cuando sea Sí antes de aceptar.",
  "Reviewed finding accepted and saved as an Analysis Record.": "Hallazgo revisado aceptado y guardado como registro de análisis.",
  "The proposal could not be saved. Your draft remains available; check browser storage and try again.": "No se pudo guardar la propuesta. Tu borrador sigue disponible; comprueba el almacenamiento e inténtalo de nuevo.",
  "AI-PROPOSED / DRAFT finding": "Hallazgo PROPUESTO POR IA / BORRADOR",
  "Check every observation against the loaded dataset. Edit as needed; accept only what your evaluation of the evidence supports.": "Comprueba cada observación con los datos cargados. Edita lo necesario; acepta solo lo que respalde tu evaluación de la evidencia.",
  "Finding / Pattern": "Hallazgo / Patrón",
  "Evidence from the Data": "Evidencia de los datos",
  "What It Could Mean": "Qué podría significar",
  "Needs More Information?": "¿Necesita más información?",
  "What additional information would help?": "¿Qué información adicional ayudaría?",
  "Accept and Save Analysis Record": "Aceptar y guardar registro de análisis",
  "Proposal rejected. No Analysis Record was created.": "Propuesta rechazada. No se creó ningún registro de análisis.",
  "Reject proposal": "Rechazar propuesta",
  "Review — Analysis Records": "Revisar — Registros de análisis",
  "Add Analysis Record": "Añadir registro de análisis",
  "Edit Analysis Record": "Editar registro de análisis",
  "New Analysis Record": "Nuevo registro de análisis",
  "Save Analysis Record": "Guardar registro de análisis",
  "Cancel edit": "Cancelar edición",
  "No Analysis Records yet.": "Aún no hay registros de análisis.",
  "Additional information": "Información adicional",
  "Edit record": "Editar registro",
  "Delete record": "Eliminar registro",
  "Delete this Analysis Record? This cannot be undone.": "¿Eliminar este registro de análisis? Esta acción no se puede deshacer.",
  "Analysis Record deleted.": "Registro de análisis eliminado.",
  "Confirm delete": "Confirmar eliminación",
  "Keep record": "Conservar registro",
  "Decide — Management Decision": "Decidir — Decisión de gestión",
  "I reviewed the underlying data and AI-supported analysis and am making this management decision based on my evaluation of the evidence.": "Revisé los datos y el análisis con apoyo de IA y tomo esta decisión de gestión según mi evaluación de la evidencia.",
  "Save Management Decision": "Guardar decisión de gestión",
  "Completed Management Decision": "Decisión de gestión completada",
  "Responsibility acknowledged: I reviewed the underlying data and AI-supported analysis and am making this management decision based on my evaluation of the evidence.": "Responsabilidad reconocida: revisé los datos y el análisis con apoyo de IA y tomo esta decisión de gestión según mi evaluación de la evidencia.",
  "Edit Decision": "Editar decisión",
  "Dataset details, loaded data, Analysis Records, and saved management decisions stay in this browser on this device. Dataset workspace prompts and pasted AI responses are temporary; student completion-history analysis is saved separately above.": "Los datos, registros de análisis y decisiones de gestión se guardan en este navegador y dispositivo. Las instrucciones y respuestas pegadas del espacio de datos son temporales; el análisis del historial personal se guarda por separado arriba.",
  "First year": "Primer año",
  "Sophomore": "Segundo año",
  "Junior": "Tercer año",
  "Senior": "Cuarto año",
  "Other": "Otro",
  "AI for Managers · Your course workspace": "IA para gerentes · Tu espacio del curso",
  "Welcome, {0}.": "Te damos la bienvenida, {0}.",
  "Welcome to your dashboard.": "Te damos la bienvenida a tu panel.",
  "Keep your academic goals in view and turn upcoming assignments into a manageable plan. Your workspace grows with you throughout the seven-week course.": "Mantén presentes tus metas académicas y convierte las próximas tareas en un plan manejable. Tu espacio crece contigo durante el curso de siete semanas.",
  "Start with Profile, then add your work in Planner. Use Research to check claims, Analysis to review evidence, Workflows to test automation, and Grace to practice asking a bounded assistant.": "Empieza con Perfil y añade tu trabajo en Planificador. Usa Investigación para comprobar afirmaciones, Análisis para revisar evidencia, Flujos de trabajo para probar automatizaciones y Grace para practicar con un asistente de alcance limitado.",
  "View your profile": "Ver tu perfil",
  "Set up your profile": "Configurar tu perfil",
  "A foundation built to grow": "Una base para crecer",
  "Add your academic information and goals in Profile. Your details stay in this browser on this device.": "Añade tu información académica y tus metas en Perfil. Tus datos permanecen en este navegador y dispositivo.",
  "Planning, Priorities & Workload": "Planificación, prioridades y carga de trabajo",
  "Build your next plan": "Prepara tu próximo plan",
  "Bring deadlines, priorities, and estimated effort together. Spot busy days and decide what needs your attention first.": "Reúne fechas de entrega, prioridades y esfuerzo estimado. Detecta días ocupados y decide qué necesita atención primero.",
  "Open Planner": "Abrir Planificador",
  "Enter your name, major, and academic year. Spaces alone do not count.": "Introduce tu nombre, carrera y año académico. Los espacios en blanco no cuentan.",
  "Your profile could not be saved. Check browser storage or available space and try again.": "No se pudo guardar tu perfil. Comprueba el almacenamiento o espacio disponible e inténtalo de nuevo.",
  "Profile saved in this browser.": "Perfil guardado en este navegador.",
  "Student profile": "Perfil del estudiante",
  "Your academic snapshot": "Tu panorama académico",
  "Basic information that helps make this dashboard yours.": "Información básica para hacer tuyo este panel.",
  "Edit profile": "Editar perfil",
  "S": "E",
  "Student": "Estudiante",
  "Name not added": "Nombre sin añadir",
  "Major": "Carrera",
  "Not added": "Sin añadir",
  "Academic year": "Año académico",
  "Academic goals": "Metas académicas",
  "No goals added yet.": "Aún no has añadido metas.",
  "Edit your profile": "Editar tu perfil",
  "Create your profile": "Crear tu perfil",
  "Add the basics below. You can return and change them at any time.": "Añade los datos básicos. Puedes volver y cambiarlos en cualquier momento.",
  "Full name": "Nombre completo",
  "e.g., Jordan Lee": "p. ej., Jordan Lee",
  "e.g., Business Administration": "p. ej., Administración de Empresas",
  "Select your year": "Selecciona tu año",
  "Add short statements about what you hope to achieve academically.": "Añade frases breves sobre lo que esperas lograr académicamente.",
  "Academic goal": "Meta académica",
  "e.g., Become more confident evaluating AI tools": "p. ej., Evaluar herramientas de IA con más confianza",
  "Remove goal {0}": "Eliminar meta {0}",
  "Remove": "Eliminar",
  "+ Add another goal": "+ Añadir otra meta",
  "Cancel": "Cancelar",
  "Save profile": "Guardar perfil",
  "AI Assistant": "Asistente de IA",
  "Workflows": "Flujos de trabajo",
  "Analysis": "Análisis",
  "Planner": "Planificador",
  "Research": "Investigación",
  "Profile": "Perfil",
  "Home": "Inicio",
  "AI for Managers Student Dashboard": "Panel del estudiante de IA para gerentes",
  "Skip to main content": "Saltar al contenido principal",
  "AI": "IA",
  "AI for Managers": "IA para gerentes",
  "Student Dashboard": "Panel del estudiante",
  "Main navigation": "Navegación principal",
  "Planner / Tasks": "Planificador / Tareas",
  "Course workspace": "Espacio del curso",
  "Weeks 1–6 of 7": "Semanas 1–6 de 7",
  "Map. Automate. Control. Test.": "Mapear. Automatizar. Controlar. Probar.",
  "English / Español": "English / Español",
  "Interface language": "Idioma de la interfaz",
  "Language changed for this visit, but could not be saved in this browser.": "El idioma cambió para esta visita, pero no se pudo guardar en este navegador.",
  "English": "English",
  "Español": "Español",
  "Student workspace": "Espacio del estudiante",
  "Open profile for {0}": "Abrir perfil de {0}",
  "Course Information": "Información del curso",
  "Coastal Life Employee Information": "Información para empleados de Coastal Life",
  "Supported": "Respaldada",
  "Boundary": "Límite",
  "Partly": "Parcialmente",
  "Saved Week 6 records could not be read. They have not been overwritten. Restore storage access or recover the data, then reload.": "No se pudieron leer los registros de la Semana 6. No se sobrescribieron. Restablece el acceso al almacenamiento o recupera los datos y recarga la página.",
  "Grace is not connected yet. The course administrator must configure the AI service.": "Grace aún no está conectada. La administración del curso debe configurar el servicio de IA.",
  "Grace is unavailable. Please try again later.": "Grace no está disponible. Inténtalo más tarde.",
  "Grace returned an invalid response. Please try again.": "Grace devolvió una respuesta no válida. Inténtalo de nuevo.",
  "Grace avatar pending": "Avatar de Grace pendiente",
  "Avatar": "Avatar",
  "pending": "pendiente",
  "Grace": "Grace",
  "Was the response supported by the selected information?": "¿La respuesta estaba respaldada por la información seleccionada?",
  "Did Grace stay within her authority?": "¿Grace se mantuvo dentro de su autoridad?",
  "Was human involvement needed?": "¿Fue necesaria la intervención humana?",
  "New conversation: {0}. Saved tests are unchanged.": "Nueva conversación: {0}. Las pruebas guardadas no cambian.",
  "Choose a knowledge source to begin.": "Elige una fuente de información para empezar.",
  "Grace took too long to respond. Please try again.": "Grace tardó demasiado en responder. Inténtalo de nuevo.",
  "Grace is unavailable. Please try again.": "Grace no está disponible. Inténtalo de nuevo.",
  "Week 6 changes could not be saved. Check browser storage or available space and try again.": "No se pudieron guardar los cambios de la Semana 6. Comprueba el almacenamiento o espacio disponible e inténtalo de nuevo.",
  "Choose a test type, complete every judgment, and explain your reasoning.": "Elige un tipo de prueba, completa todos los juicios y explica tu razonamiento.",
  "One test of each type is required. Edit or delete the existing test of this type first.": "Se requiere una prueba de cada tipo. Primero edita o elimina la prueba existente de este tipo.",
  "Test saved in this browser. Review and save Assistant Evaluation after test changes.": "Prueba guardada en este navegador. Revisa y guarda la evaluación del asistente después de cambiar las pruebas.",
  "Undergraduate Week 6": "Semana 6 de pregrado",
  "Ask a bounded assistant, inspect her sources, and make your own judgments.": "Pregunta a un asistente de alcance limitado, consulta sus fuentes y formula tus propios juicios.",
  "Choose a source, expand the reference, and ask a question. Compare Grace’s answer with the approved information; her response is not an approval or a decision.": "Elige una fuente, abre la referencia y haz una pregunta. Compara la respuesta de Grace con la información aprobada; su respuesta no es una aprobación ni una decisión.",
  "Chat with Grace": "Conversar con Grace",
  "Knowledge source": "Fuente de información",
  "Choose a source": "Elegir una fuente",
  "Changing sources clears the chat and unsaved test draft. Each question is answered independently using only the selected reference; previous messages are not sent.": "Cambiar de fuente borra la conversación y el borrador de prueba sin guardar. Cada pregunta se responde de forma independiente usando solo la referencia seleccionada; no se envían mensajes anteriores.",
  "Read selected information": "Leer información seleccionada",
  "Optional example questions": "Preguntas de ejemplo opcionales",
  "Choose any example or type your own. Only two saved tests are required.": "Elige un ejemplo o escribe tu pregunta. Solo se requieren dos pruebas guardadas.",
  "Grace conversation": "Conversación con Grace",
  "Ask about {0}. Grace can explain supplied information; she cannot approve requests or invent missing policies.": "Pregunta sobre {0}. Grace puede explicar la información proporcionada; no puede aprobar solicitudes ni inventar políticas ausentes.",
  "Choose which information Grace may use before asking a question.": "Elige qué información puede usar Grace antes de preguntar.",
  "You": "Tú",
  "Evaluate this response": "Evaluar esta respuesta",
  "Grace is thinking…": "Grace está pensando…",
  "Ask Grace": "Preguntar a Grace",
  "Your question": "Tu pregunta",
  "Your question is sent to Cloudflare Workers AI. Use fictional exercise information; keep personal details out of the chat.": "Tu pregunta se envía a Cloudflare Workers AI. Usa información ficticia del ejercicio; no incluyas datos personales.",
  "Clear conversation": "Borrar conversación",
  "Send": "Enviar",
  "Use the Coastal Life source in the chat above, evaluate a response, and save one Supported test and one Boundary test before completing your evaluation.": "Usa la fuente Coastal Life en la conversación, evalúa una respuesta y guarda una prueba Respaldada y una de Límite antes de completar tu evaluación.",
  "Two saved tests": "Dos pruebas guardadas",
  "Use Coastal Life Employee Information. Save one Supported test and one Boundary test (missing information or human involvement). You make every evaluation judgment.": "Usa la información para empleados de Coastal Life. Guarda una prueba Respaldada y una de Límite (información ausente o intervención humana). Tú realizas todos los juicios de evaluación.",
  "of 2 saved · Supported:": "de 2 guardadas · Respaldada:",
  "saved": "guardada",
  "needed": "necesaria",
  "· Boundary:": "· Límite:",
  "Evaluate Grace response": "Evaluar respuesta de Grace",
  "Edit test evaluation": "Editar evaluación de prueba",
  "Question asked:": "Pregunta realizada:",
  "Grace response:": "Respuesta de Grace:",
  "Source: Coastal Life Employee Information. The generated question/response pair is retained unchanged.": "Fuente: información para empleados de Coastal Life. La pregunta y la respuesta generada se conservan sin cambios.",
  "Test type": "Tipo de prueba",
  "Choose": "Elegir",
  "Student explanation/reasoning": "Explicación / razonamiento del estudiante",
  "Cancel evaluation": "Cancelar evaluación",
  "Save test": "Guardar prueba",
  "{0} test": "Prueba {0}",
  "test": "prueba",
  "Question:": "Pregunta:",
  "Grace:": "Grace:",
  "Source: Coastal Life Employee Information": "Fuente: información para empleados de Coastal Life",
  "Edit": "Editar",
  "Delete": "Eliminar",
  "Confirm test deletion": "Confirmar eliminación de prueba",
  "Delete this test? Review Assistant Evaluation again after replacing it.": "¿Eliminar esta prueba? Revisa otra vez la evaluación del asistente después de sustituirla.",
  "Test deleted.": "Prueba eliminada.",
  "Keep test": "Conservar prueba",
  "Assistant Evaluation": "Evaluación del asistente",
  "Reflect on both tests, then save your evaluation.": "Reflexiona sobre ambas pruebas y guarda tu evaluación.",
  "Complete both required tests before saving your evaluation.": "Completa ambas pruebas requeridas antes de guardar tu evaluación.",
  "Complete both tests and both evaluation responses.": "Completa ambas pruebas y las dos respuestas de evaluación.",
  "Assistant Evaluation saved in this browser.": "Evaluación del asistente guardada en este navegador.",
  "Based on your testing, what types of questions can Grace reasonably help with?": "Según tus pruebas, ¿con qué tipos de preguntas puede ayudar Grace razonablemente?",
  "When should Grace acknowledge that she does not have enough information or refer the employee to a human?": "¿Cuándo debe Grace reconocer que no tiene suficiente información o remitir al empleado a una persona?",
  "Save Assistant Evaluation": "Guardar evaluación del asistente",
  "Saved evaluation available in this browser. Save again after editing.": "Evaluación guardada disponible en este navegador. Vuelve a guardar después de editar.",
  "When does my PTO increase?": "¿Cuándo aumenta mi PTO?",
  "How much PTO do I receive after three years?": "¿Cuánto PTO recibo después de tres años?",
  "How much PTO do I receive after six years?": "¿Cuánto PTO recibo después de seis años?",
  "How far in advance should I request PTO?": "¿Con cuánta anticipación debo solicitar PTO?",
  "Can Grace approve my PTO request?": "¿Puede Grace aprobar mi solicitud de PTO?",
  "I'm running late for my shift this morning. What should I do?": "Voy a llegar tarde a mi turno esta mañana. ¿Qué debo hacer?",
  "Can I have a coworker tell my supervisor that I'm running late?": "¿Puede un compañero avisar a mi supervisor que voy a llegar tarde?",
  "Can I change tomorrow's shift without supervisor approval?": "¿Puedo cambiar el turno de mañana sin la aprobación del supervisor?",
  "How many paid sick days do Coastal Life employees receive?": "¿Cuántos días pagados por enfermedad reciben los empleados de Coastal Life?",
  "Does unused PTO carry into next year?": "¿El PTO no utilizado se transfiere al año siguiente?",
  "When am I eligible for health insurance?": "¿Cuándo reúno los requisitos para el seguro médico?",
  "The dishwasher at a rental is not working. What should I do?": "El lavavajillas de una propiedad de alquiler no funciona. ¿Qué debo hacer?",
  "A guest says they smell gas inside the rental. Should I just enter a normal maintenance request?": "Un huésped dice que huele a gas dentro de la propiedad. ¿Basta con registrar una solicitud de mantenimiento normal?",
  "There is active water coming into a property. Should I treat it like an ordinary maintenance request?": "Está entrando agua en una propiedad. ¿Debo tratarlo como mantenimiento rutinario?",
  "Completed": "Completada",
  "Overdue": "Vencida",
  "Due today": "Vence hoy",
  "Upcoming": "Próxima",
  "Enter a valid Completed On date (1900 or later).": "Introduce una fecha de finalización válida (1900 o posterior).",
  "Enter a task title; spaces alone are not a title.": "Introduce un título de tarea; no puede contener solo espacios.",
  "Keep the task title to 160 characters or fewer.": "El título debe tener un máximo de 160 caracteres.",
  "Enter a valid due date (1900 or later).": "Introduce una fecha de entrega válida (1900 o posterior).",
  "Enter estimated hours between 0 and 1,000.": "Introduce horas estimadas entre 0 y 1000.",
  "Choose High, Medium, or Low priority.": "Elige prioridad Alta, Media o Baja.",
  "Use up to 100 characters for category and 1,000 for notes.": "Usa hasta 100 caracteres para la categoría y 1000 para las notas.",
  "Saved tasks could not be read. Your stored data has not been replaced. Restore browser storage access or recover the saved data, then reload.": "No se pudieron leer las tareas guardadas. Tus datos no se han sustituido. Restablece el acceso al almacenamiento o recupera los datos y recarga la página.",
  "Early": "Anticipada",
  "Late": "Tardía",
  "On Time": "A tiempo",
  "All": "Todas",
  "Tasks could not be saved in this browser. Your changes have not been applied. Check browser storage or available space and try again.": "No se pudieron guardar las tareas. No se aplicaron tus cambios. Comprueba el almacenamiento o espacio disponible e inténtalo de nuevo.",
  "Task saved in this browser.": "Tarea guardada en este navegador.",
  "Week 2 · Planning, Priorities & Workload": "Semana 2 · Planificación, prioridades y carga de trabajo",
  "Make room for what matters. Review deadlines, effort, and your priorities.": "Haz espacio para lo importante. Revisa fechas, esfuerzo y prioridades.",
  "+ Add task": "+ Añadir tarea",
  "Add an assignment, its due date, and estimated effort. Set your priorities, review workload, and mark finished work complete. Use Analysis later to review completion patterns.": "Añade una tarea, su fecha de entrega y esfuerzo estimado. Define prioridades, revisa la carga y marca el trabajo terminado. Usa Análisis después para revisar patrones de finalización.",
  "Task overview": "Resumen de tareas",
  "Upcoming, including today": "Próximas, incluido hoy",
  "Unfinished tasks": "Tareas pendientes",
  "hours outstanding": "horas pendientes",
  "Ready to review or reopen": "Listas para revisar o reabrir",
  "Total remaining workload": "Carga de trabajo restante total",
  "hrs": "h",
  "All unfinished tasks": "Todas las tareas pendientes",
  "Edit task": "Editar tarea",
  "Add a task or assignment": "Añadir tarea o trabajo",
  "Title, due date, hours, and priority are required. Estimates can be revised.": "Se requieren título, fecha de entrega, horas y prioridad. Puedes revisar las estimaciones.",
  "Task title": "Título de la tarea",
  "Course / project / category (optional)": "Curso / proyecto / categoría (opcional)",
  "Due date": "Fecha de entrega",
  "Due through the end of this date, in your local time.": "Vence al final de esta fecha, según tu hora local.",
  "Completed On": "Fecha de finalización",
  "Enter the actual local calendar date. Leave blank if not recorded.": "Introduce la fecha local real. Deja el campo vacío si no se registró.",
  "Estimated remaining hours": "Horas restantes estimadas",
  "Decimals are welcome, e.g. 0.5 for 30 minutes.": "Puedes usar decimales, p. ej., 0.5 para 30 minutos.",
  "Priority": "Prioridad",
  "Brief notes (optional)": "Notas breves (opcional)",
  "Save task": "Guardar tarea",
  "Your tasks": "Tus tareas",
  "shown": "mostradas",
  "Show": "Mostrar",
  "Sort by": "Ordenar por",
  "Deadline first": "Fecha de entrega primero",
  "Priority first": "Prioridad primero",
  "No tasks in this view": "No hay tareas en esta vista",
  "A clear place to start": "Un punto de partida claro",
  "Choose another view to see your tasks.": "Elige otra vista para ver tus tareas.",
  "Add an assignment, estimate the effort, and choose its priority. Your plan starts here.": "Añade una tarea, estima el esfuerzo y elige su prioridad. Tu plan empieza aquí.",
  "priority": "prioridad",
  "Due": "Vence",
  "hrs estimated": "h estimadas",
  "Completed On {0}": "Finalizada el {0}",
  "Completion date not recorded": "Fecha de finalización no registrada",
  "· {0} · {1} calendar days{2}": "· {0} · {1} días naturales{2}",
  "early/late": "de anticipación/retraso",
  ". Edit to update the completion date.": ". Edita para actualizar la fecha de finalización.",
  "Task reopened.": "Tarea reabierta.",
  "Task completed.": "Tarea completada.",
  "Mark {0} {1}": "Marcar {0} como {1}",
  "Mark complete": "Marcar como completada",
  "Edit {0}": "Editar {0}",
  "Duplicate draft: choose a new due date and revise any details before saving.": "Borrador duplicado: elige otra fecha de entrega y revisa los datos antes de guardar.",
  "Duplicate {0}": "Duplicar {0}",
  "Duplicate task": "Duplicar tarea",
  "Delete {0}": "Eliminar {0}",
  "Delete “": "¿Eliminar «",
  "”? This cannot be undone.": "»? Esta acción no se puede deshacer.",
  "Other tasks require this prerequisite. Deleting it will leave a missing-reference warning until you revise those dependencies.": "Otras tareas requieren este requisito previo. Eliminarlo dejará un aviso de referencia ausente hasta que revises esas dependencias.",
  "Task deleted.": "Tarea eliminada.",
  "Keep task": "Conservar tarea",
  "Planning overview": "Resumen de planificación",
  "Next 7 days": "Próximos 7 días",
  "Estimated hours grouped by due date, not scheduled work sessions.": "Horas estimadas agrupadas por fecha de entrega, no por sesiones de trabajo.",
  "hrs ·": "h ·",
  "task": "tarea",
  "tasks": "tareas",
  "Deadlines clustered: 3+ on this date": "Fechas concentradas: 3 o más en este día",
  "Planning Support": "Apoyo a la planificación",
  "Use the two prompt features above with your approved external AI tool. Review its assumptions and change its recommendations when needed.": "Usa las dos funciones de instrucciones anteriores con tu herramienta de IA aprobada. Revisa sus supuestos y cambia sus recomendaciones cuando sea necesario.",
  "Parsing, dependency checks, workload totals, sorting, and duplication are ordinary rules, not AI. Priority is importance; sequence also depends on prerequisites and available time.": "El análisis de formato, las dependencias, los totales, la ordenación y la duplicación son reglas normales, no IA. La prioridad indica importancia; la secuencia también depende de requisitos previos y tiempo disponible.",
  "Saved only in this browser on this device. Clearing site data removes your profile and tasks. No account or cloud sync.": "Guardado solo en este navegador y dispositivo. Borrar los datos del sitio elimina tu perfil y tareas. Sin cuenta ni sincronización en la nube.",
  "Must complete first": "Completar primero",
  "Prerequisites are separate from priority. Select all that apply. Completed prerequisites are considered satisfied and are not shown here.": "Los requisitos previos son distintos de la prioridad. Selecciona todos los que correspondan. Los completados se consideran satisfechos y no aparecen aquí.",
  "No unfinished prerequisite tasks available.": "No hay tareas pendientes disponibles como requisitos previos.",
  "Missing or invalid prerequisite:": "Requisito previo ausente o no válido:",
  "— uncheck to remove": "— desmarca para eliminar",
  "Prompt copied. Paste it into your approved AI tool.": "Instrucción copiada. Pégala en tu herramienta de IA aprobada.",
  "Copy was unavailable. Select the prompt text below and copy it manually.": "No se pudo copiar. Selecciona la instrucción siguiente y cópiala manualmente.",
  "Use your course-approved AI tool separately. This dashboard does not call an AI service. Copying information into that tool shares it with that service; omit sensitive information and check course policy. No profile information is included automatically. AI output can contain mistakes and assumptions.": "Usa por separado la herramienta de IA aprobada para el curso. Este panel no llama a un servicio de IA. Copiar información en esa herramienta la comparte con ese servicio; omite información sensible y consulta las normas del curso. No se incluye información de perfil automáticamente. Las respuestas de IA pueden contener errores y supuestos.",
  "Today & tomorrow": "Hoy y mañana",
  "hours due ·": "horas con entrega ·",
  "deadline": "fecha de entrega",
  "deadlines": "fechas de entrega",
  "Deadlines clustered:": "Fechas concentradas:",
  "across two dates. Task count alone does not establish heavy workload.": "en dos fechas. La cantidad de tareas por sí sola no demuestra una carga excesiva.",
  "Effort grouped by due date, not a work schedule. Set available time in Prepare AI Planning Prompt. Overdue work is separate and also needs attention.": "Esfuerzo agrupado por fecha de entrega, no un horario de trabajo. Define el tiempo disponible en Preparar instrucción de planificación para IA. El trabajo vencido se muestra aparte y también requiere atención.",
  "Also review": "Revisa también",
  "overdue": "vencidas",
  "hrs).": "h).",
  "Planning summary": "Resumen de planificación",
  "Review Planner": "Revisar Planificador",
  "upcoming (including today) ·": "próximas (incluido hoy) ·",
  "high-priority tasks": "tareas de prioridad alta",
  "Deadlines needing attention": "Fechas que requieren atención",
  "No unfinished tasks. Add work in Planner when you are ready.": "No hay tareas pendientes. Añade trabajo en Planificador cuando lo necesites.",
  "Needs review: your AI planning prompt or recommendation is based on older task, time, or date information.": "Requiere revisión: tu instrucción o recomendación de planificación se basa en datos anteriores de tareas, tiempo o fechas.",
  "{0}: missing prerequisite ({1}). Edit dependencies to resolve it.": "{0}: falta el requisito previo ({1}). Edita las dependencias para resolverlo.",
  "{0}: finish {1} first.": "{0}: termina primero {1}.",
  "{0}: circular dependency. Remove a prerequisite link to break the loop.": "{0}: dependencia circular. Elimina un vínculo de requisito previo para romper el ciclo.",
  "{0} hours estimated; available time unknown.": "{0} horas estimadas; tiempo disponible desconocido.",
  "{0} hours estimated / {1} hours available — exceeds capacity by {2} hours.": "{0} horas estimadas / {1} horas disponibles — supera la capacidad en {2} horas.",
  "{0} hours estimated / {1} hours available — fits the time budget on estimates alone.": "{0} horas estimadas / {1} horas disponibles — cabe en el tiempo disponible según las estimaciones.",
  "UNKNOWN": "DESCONOCIDO",
  "Paste the structured AI response first.": "Pega primero la respuesta estructurada de IA.",
  "Response is too large. Import a smaller batch (100,000 characters maximum).": "La respuesta es demasiado grande. Importa un lote más pequeño (máximo 100 000 caracteres).",
  "This is not valid JSON. Ask your AI tool to return only the requested JSON, then paste the complete response.": "El JSON no es válido. Pide a tu herramienta de IA solo el JSON solicitado y pega la respuesta completa.",
  "Expected a tasks list containing 1–100 proposed tasks.": "Se esperaba una lista tasks con entre 1 y 100 tareas propuestas.",
  "Each proposed task must be an object with task fields.": "Cada tarea propuesta debe ser un objeto con campos de tarea.",
  "Every proposed task needs a unique text id (such as T1 or T2).": "Cada tarea propuesta necesita un identificador de texto único (como T1 o T2).",
  "Dependencies missing or malformed; confirm prerequisites.": "Dependencias ausentes o incorrectas; confirma los requisitos previos.",
  "AI-proposed effort and priority: confirm or revise both.": "Esfuerzo y prioridad propuestos por IA: confirma o revisa ambos.",
  "Missing or questionable date. Original: {0}": "Fecha ausente o dudosa. Original: {0}",
  "Date is in the past. Confirm it is an overdue task, not a date error.": "La fecha está en el pasado. Confirma que es una tarea vencida y no un error de fecha.",
  "Missing or unusual effort estimate; review the hours.": "Estimación de esfuerzo ausente o inusual; revisa las horas.",
  "AI-proposed or inferred dependencies: verify every prerequisite.": "Dependencias propuestas o inferidas por IA: verifica cada requisito previo.",
  "No source excerpt supplied. Check against the original assignment information.": "No se proporcionó extracto de la fuente. Comprueba la información original de la tarea.",
  "Possible duplicate: a task with this title already exists or appears elsewhere in this import.": "Posible duplicado: ya existe una tarea con este título o aparece en otra parte de esta importación.",
  "Confirm that you checked the proposal and its review flags before approving.": "Confirma que comprobaste la propuesta y sus avisos antes de aprobarla.",
  "This proposal is already saved.": "Esta propuesta ya está guardada.",
  "Resolve missing or circular dependencies first. Approve prerequisite proposals before tasks that depend on them.": "Resuelve primero las dependencias ausentes o circulares. Aprueba los requisitos previos antes de las tareas que dependen de ellos.",
  "Expected sequence, assumptions, and unscheduled lists in the AI response.": "Se esperaban listas sequence, assumptions y unscheduled en la respuesta de IA.",
  "This plan is too large. Use a smaller selection.": "Este plan es demasiado grande. Usa una selección más pequeña.",
  "The plan references an unknown task id. Ask the AI to use only the ids in your prompt.": "El plan hace referencia a una tarea desconocida. Pide a la IA que use solo los identificadores de tu instrucción.",
  "The plan contains a duplicate task id. Each task may appear only once.": "El plan contiene un identificador duplicado. Cada tarea solo puede aparecer una vez.",
  "The plan assigns work to an already completed task. Revise the response.": "El plan asigna trabajo a una tarea ya completada. Revisa la respuesta.",
  "Each recommendation needs a short reason (up to 2,000 characters).": "Cada recomendación necesita un motivo breve (hasta 2000 caracteres).",
  "Each sequence item needs day: today or tomorrow.": "Cada elemento de la secuencia necesita day: today o tomorrow.",
  "Omitted by AI — student review required.": "Omitido por IA — requiere revisión del estudiante.",
  "Missing task {0}; review this plan.": "Falta la tarea {0}; revisa este plan.",
  "{0} is now completed; review this plan.": "{0} ya está completada; revisa este plan.",
  "{0}: {1} must be scheduled first.": "{0}: primero debe programarse {1}.",
  "Sequence places today after tomorrow; review the order.": "La secuencia coloca hoy después de mañana; revisa el orden.",
  "{0}: planned after its due date.": "{0}: programada después de su fecha de entrega.",
  "Pending": "Pendiente",
  "Verified": "Verificada",
  "Partly verified": "Parcialmente verificada",
  "Not verified": "No verificada",
  "Invalid record.": "Registro no válido.",
  "Enter a research question or topic.": "Introduce una pregunta o tema de investigación.",
  "Enter a research area or category.": "Introduce un área o categoría de investigación.",
  "Enter a claim to verify.": "Introduce una afirmación para verificar.",
  "Select a valid verification status.": "Selecciona un estado de verificación válido.",
  "Source URL must be a string.": "La URL de la fuente debe ser texto.",
  "Research question must be 500 characters or fewer.": "La pregunta debe tener un máximo de 500 caracteres.",
  "Research area must be 100 characters or fewer.": "El área debe tener un máximo de 100 caracteres.",
  "Claim must be 2,000 characters or fewer.": "La afirmación debe tener un máximo de 2000 caracteres.",
  "Source URL must be 500 characters or fewer.": "La URL debe tener un máximo de 500 caracteres.",
  "Enter verification source information.": "Introduce información de la fuente de verificación.",
  "Enter what you found after checking the source.": "Introduce lo que encontraste al comprobar la fuente.",
  "Source information must be 2,000 characters or fewer.": "La información de la fuente debe tener un máximo de 2000 caracteres.",
  "Finding must be 2,000 characters or fewer.": "El hallazgo debe tener un máximo de 2000 caracteres.",
  "Source must be a string.": "La fuente debe ser texto.",
  "Finding must be a string.": "El hallazgo debe ser texto.",
  "Saved research records could not be read. Your stored data has not been replaced. Restore browser storage access or recover the saved data, then reload.": "No se pudieron leer los registros de investigación. Tus datos no se han sustituido. Restablece el acceso al almacenamiento o recupera los datos y recarga la página.",
  "Research records could not be saved in this browser. Your changes have not been applied. Check browser storage or available space and try again.": "No se pudieron guardar los registros de investigación. No se aplicaron tus cambios. Comprueba el almacenamiento o espacio disponible e inténtalo de nuevo.",
  "Research record saved in this browser.": "Registro de investigación guardado en este navegador.",
  "Week 3 · Research & Verification": "Semana 3 · Investigación y verificación",
  "Research & Verification": "Investigación y verificación",
  "Evaluate claims, check sources, and record what you found. Retain responsibility for your judgment.": "Evalúa afirmaciones, comprueba fuentes y registra lo que encontraste. Conserva la responsabilidad de tu juicio.",
  "+ Add research record": "+ Añadir registro de investigación",
  "Use this workspace for any paper, project, product, or claim. Add a research record, check a source, and record what the evidence supports.": "Usa este espacio para cualquier trabajo, proyecto, producto o afirmación. Añade un registro, comprueba una fuente y anota qué respalda la evidencia.",
  "Coastal Life Management Application — Research example": "Aplicación de gestión de Coastal Life — Ejemplo de investigación",
  "Example question: Should Coastal Life expand into vacation rental management in Charleston?": "Pregunta de ejemplo: ¿Debería Coastal Life expandirse a la gestión de alquileres vacacionales en Charleston?",
  "Possible research areas: market demand, competition, and rules and restrictions. Use the same records below to investigate claims and verify sources. Records can belong to any research topic.": "Posibles áreas: demanda del mercado, competencia y normas y restricciones. Usa los mismos registros para investigar afirmaciones y verificar fuentes. Los registros pueden ser de cualquier tema.",
  "Edit research record": "Editar registro de investigación",
  "Add a research record": "Añadir un registro de investigación",
  "Research question, area, and claim are always required. Source and finding are optional while Pending; they become required when you select a verification outcome.": "La pregunta, el área y la afirmación son obligatorias. La fuente y el hallazgo son opcionales mientras esté Pendiente; se requieren al seleccionar un resultado de verificación.",
  "Research question or topic (required)": "Pregunta o tema de investigación (obligatorio)",
  "e.g., What evidence supports the claim I am researching?": "p. ej., ¿Qué evidencia respalda la afirmación que investigo?",
  "Research area or category (required)": "Área o categoría de investigación (obligatoria)",
  "e.g., Market demand, Competition, Rules and restrictions": "p. ej., Demanda del mercado, competencia, normas y restricciones",
  "Verification status (required)": "Estado de verificación (obligatorio)",
  "Pending: verification is incomplete. Check a source before selecting a final status.": "Pendiente: la verificación está incompleta. Comprueba una fuente antes de seleccionar un estado final.",
  "Verified: the source supports the full claim.": "Verificada: la fuente respalda toda la afirmación.",
  "Partly verified: only part of the claim is supported or qualifications remain.": "Parcialmente verificada: solo parte está respaldada o quedan salvedades.",
  "Not verified: the evidence does not adequately support the claim.": "No verificada: la evidencia no respalda adecuadamente la afirmación.",
  "Claim to check (required)": "Afirmación que comprobar (obligatoria)",
  "State the specific claim you are investigating.": "Indica la afirmación específica que investigas.",
  "Verification source": "Fuente de verificación",
  "(optional)": "(opcional)",
  "(required)": "(obligatorio)",
  "Describe where you checked this claim. Include author, publication, date, and relevant details.": "Describe dónde comprobaste esta afirmación. Incluye autor, publicación, fecha y detalles pertinentes.",
  "Optional while pending.": "Opcional mientras esté pendiente.",
  "Required for this status.": "Obligatorio para este estado.",
  "Source URL (optional)": "URL de la fuente (opcional)",
  "e.g., https://example.com/article": "p. ej., https://example.com/article",
  "Not all sources have URLs. Document the source in the field above.": "No todas las fuentes tienen URL. Documenta la fuente en el campo anterior.",
  "What you found after checking the source": "Lo que encontraste al comprobar la fuente",
  "Describe what the source actually established. Be specific about what supports or does not support the claim.": "Describe qué estableció realmente la fuente. Especifica qué respalda o no respalda la afirmación.",
  "This is your judgment based on what the source actually says, not what the source claims or what you hoped to find.": "Este es tu juicio basado en lo que la fuente realmente dice, no en lo que afirma o lo que esperabas encontrar.",
  "Save record": "Guardar registro",
  "Saved research records": "Registros de investigación guardados",
  "record": "registro",
  "s": "s",
  "No research records yet": "Aún no hay registros de investigación",
  "Create your first record to begin researching and verifying claims.": "Crea tu primer registro para empezar a investigar y verificar afirmaciones.",
  "Claim": "Afirmación",
  "Verification": "Verificación",
  "Source:": "Fuente:",
  "URL:": "URL:",
  "Finding:": "Hallazgo:",
  "Edit research record: {0}": "Editar registro de investigación: {0}",
  "Delete research record: {0}": "Eliminar registro de investigación: {0}",
  "Delete this research record? This cannot be undone.": "¿Eliminar este registro de investigación? Esta acción no se puede deshacer.",
  "Research record deleted.": "Registro de investigación eliminado.",
  "Saved only in this browser on this device. Clearing site data removes your research records. No account or cloud sync.": "Guardado solo en este navegador y dispositivo. Borrar los datos del sitio elimina tus registros de investigación. Sin cuenta ni sincronización en la nube.",
  "Evidence supports": "La evidencia respalda",
  "AI assumptions": "Supuestos de IA",
  "My decision": "Mi decisión",
  "Saved student analysis could not be read. It has not been overwritten. Restore browser storage access or recover the data, then reload.": "No se pudo leer el análisis personal guardado. No se sobrescribió. Restablece el acceso al almacenamiento o recupera los datos y recarga la página.",
  "Student analysis saved in this browser.": "Análisis personal guardado en este navegador.",
  "Student analysis could not be saved. Check browser storage or available space and try again.": "No se pudo guardar el análisis personal. Comprueba el almacenamiento o espacio disponible e inténtalo de nuevo.",
  "Undergraduate Week 4 — Student Dashboard Analysis": "Semana 4 de pregrado — Análisis del panel del estudiante",
  "Use information about your own academic activity or performance to identify a pattern, evaluate what AI says that pattern means, and decide what—if anything—you should do about it.": "Usa información de tu actividad o desempeño académico para identificar un patrón, evaluar qué dice la IA sobre su significado y decidir qué hacer, si corresponde.",
  "Planner supports forward-looking planning and prioritization. Analysis reviews past completion evidence and patterns.": "El Planificador apoya la planificación y las prioridades futuras. Análisis revisa evidencia y patrones de finalización pasados.",
  "DATA — Completion history": "DATOS — Historial de finalización",
  "Early:": "Anticipadas:",
  "· On Time:": "· A tiempo:",
  "· Late:": "· Tardías:",
  "Before the due date is Early; the same date is On Time; after it is Late. Calendar-day differences are calculated by the dashboard, not AI. These totals describe timing, not grades or causes.": "Antes de la fecha de entrega es Anticipada; en la misma fecha es A tiempo; después es Tardía. El panel calcula los días naturales, no la IA. Estos totales describen fechas, no calificaciones ni causas.",
  "Completion history table": "Tabla de historial de finalización",
  "Eligible completed Planner assignments": "Tareas completadas del Planificador aptas para análisis",
  "Title": "Título",
  "Classification": "Clasificación",
  "Calendar days early/late": "Días naturales de anticipación/retraso",
  "(same date)": "(misma fecha)",
  "No eligible completion records yet.": "Aún no hay registros de finalización aptos para análisis.",
  "Dates needed before analysis": "Fechas necesarias antes del análisis",
  "Valid due and completion dates needed": "Se necesitan fechas válidas de entrega y finalización",
  ". Edit this completed item in Planner to enter the actual date.": ". Edita este elemento completado en Planificador para indicar la fecha real.",
  "ANALYZE — External AI pattern review": "ANALIZAR — Revisar patrones con IA externa",
  "Generate and copy the evidence prompt into your course-approved external AI tool, then paste its response below. This dashboard makes no AI/API requests.": "Genera y copia la instrucción con evidencia en tu herramienta de IA externa aprobada y pega su respuesta abajo. Este panel no realiza solicitudes de IA/API.",
  "Generate completion-history prompt": "Generar instrucción del historial de finalización",
  "Completion-history AI prompt": "Instrucción para IA del historial de finalización",
  "This saved prompt is an evidence snapshot. If Planner records change, generate a new prompt and review your response and decision against it.": "Esta instrucción guardada es una instantánea de la evidencia. Si cambian los registros del Planificador, genera otra instrucción y revisa la respuesta y tu decisión con ella.",
  "Completion-history prompt copied.": "Instrucción del historial copiada.",
  "Copy completion-history prompt": "Copiar instrucción del historial",
  "Paste AI completion-history response": "Pegar respuesta de IA sobre el historial",
  "REVIEW & DECIDE — Your judgment": "REVISAR Y DECIDIR — Tu criterio",
  "After comparing the AI analysis with your actual data and your own context, what does the evidence support, what—if anything—did AI assume, and what will you do (if anything)?": "Tras comparar el análisis de IA con tus datos reales y tu contexto, ¿qué respalda la evidencia, qué supuso la IA, si acaso, y qué harás, si corresponde?",
  "Save student analysis": "Guardar análisis personal",
  "Save to keep your AI response, review, and decision in this browser on this device. The generated evidence prompt is also saved.": "Guarda para conservar la respuesta de IA, tu revisión y decisión en este navegador y dispositivo. La instrucción generada también se guarda.",
  "Saved planning data could not be read. It has not been overwritten. Restore browser storage access or recover the data, then reload.": "No se pudieron leer los datos de planificación. No se sobrescribieron. Restablece el acceso al almacenamiento o recupera los datos y recarga la página.",
  "Could not save planning changes in this browser. Check available storage and try again.": "No se pudieron guardar los cambios de planificación. Comprueba el almacenamiento disponible e inténtalo de nuevo.",
  "— Due": "— Vence",
  "Weekly Assignment Briefing": "Informe semanal de tareas",
  "MAP:": "MAPEAR:",
  "Check incomplete Planner assignments for past-due dates and dates due this week.": "Comprueba las tareas pendientes del Planificador con fechas vencidas o de esta semana.",
  "AUTOMATE:": "AUTOMATIZAR:",
  "The Sunday check covers Sunday through Saturday. This briefing appears automatically when you use this tab on Sunday or later in that week, using current Planner data. It refreshes as dates and Planner records change while the dashboard is in use. Nothing runs while the dashboard is closed.": "La revisión del domingo cubre de domingo a sábado. Este informe aparece automáticamente al usar esta pestaña el domingo o después durante esa semana, con datos actuales del Planificador. Se actualiza cuando cambian las fechas y los registros mientras usas el panel. No se ejecuta nada con el panel cerrado.",
  "CONTROL:": "CONTROLAR:",
  "Automation handles checking dates/status and organizing Past Due and Due This Week assignments. You handle priorities, scheduling decisions, academic work, and deciding what action to take. This is date/status filtering, not AI; list order does not recommend what to work on first.": "La automatización comprueba fechas y estados y organiza las tareas vencidas y de esta semana. Tú gestionas prioridades, horarios, trabajo académico y acciones. Es filtrado por fecha y estado, no IA; el orden no recomienda qué hacer primero.",
  "Week:": "Semana:",
  "through": "hasta",
  "· As of": "· Al",
  "(local calendar dates).": "(fechas del calendario local).",
  "Past Due — Needs Attention": "Vencidas — Requieren atención",
  "No incomplete past-due assignments.": "No hay tareas pendientes vencidas.",
  "Due This Week": "Entregas de esta semana",
  "Incomplete assignments due today through Saturday, including both dates.": "Tareas pendientes que vencen entre hoy y el sábado, ambos incluidos.",
  "No incomplete assignments due in the rest of this week.": "No hay tareas pendientes con entrega en el resto de esta semana.",
  "TEST:": "PROBAR:",
  "Run the same rule now and compare the assignments above with Planner.": "Ejecuta la misma regla ahora y compara las tareas anteriores con el Planificador.",
  "Test Automation": "Probar automatización",
  "Automation tested against current Planner data:": "Automatización probada con datos actuales del Planificador:",
  "past due;": "vencidas;",
  "due this week. Results are shown above.": "con entrega esta semana. Los resultados aparecen arriba.",
  "Uses Planner records saved in this browser. No separate assignment records are created.": "Usa los registros del Planificador guardados en este navegador. No se crean registros de tareas separados.",
  "Automation": "Automatización",
  "AI Support": "Apoyo de IA",
  "Human": "Persona",
  "Housekeeping": "Limpieza",
  "Guest reports sand was left in the bathtub after housekeeping.": "El huésped informa que quedó arena en la bañera después de la limpieza.",
  "Maintenance": "Mantenimiento",
  "Guest reports the dishwasher is not working.": "El huésped informa que el lavavajillas no funciona.",
  "Guest Services": "Atención al huésped",
  "Guest reports that requested linens were not delivered.": "El huésped informa que no se entregó la ropa de cama solicitada.",
  "Management/Exception": "Gerencia/Excepción",
  "Guest reports bugs throughout the property and is requesting management assistance.": "El huésped informa de insectos en toda la propiedad y solicita ayuda de la gerencia.",
  "Wi-Fi outage": "Interrupción de Wi-Fi",
  "AC failure": "Falla del aire acondicionado",
  "Water coming through a ceiling": "Agua entrando por el techo",
  "Broken bedroom lamp": "Lámpara del dormitorio averiada",
  "Vacation Rentals/Guest Services": "Alquileres vacacionales/Atención al huésped",
  "Property Manager": "Gerente de la propiedad",
  "Held for Human Review": "Pendiente de revisión humana",
  "Automatically Routed": "Derivado automáticamente",
  "Workflow behaved as intended": "El flujo funcionó como se esperaba",
  "Wrong routing": "Derivación incorrecta",
  "Unclear step": "Paso poco claro",
  "Inappropriate automation": "Automatización inadecuada",
  "Missing human review": "Falta revisión humana",
  "Escalation/control issue": "Problema de escalamiento/control",
  "Another exception": "Otra excepción",
  "Saved Workflows data could not be read. It has not been overwritten. Restore browser storage access or recover the data, then reload.": "No se pudieron leer los datos de Flujos de trabajo. No se sobrescribieron. Restablece el acceso al almacenamiento o recupera los datos y recarga la página.",
  "What did you automate or make AI-supported?": "¿Qué automatizaste o apoyaste con IA?",
  "What did you intentionally keep under human control?": "¿Qué mantuviste intencionalmente bajo control humano?",
  "What did testing reveal?": "¿Qué revelaron las pruebas?",
  "What did you change or what would you change?": "¿Qué cambiaste o cambiarías?",
  "Why is the final workflow an appropriate management decision?": "¿Por qué el flujo final es una decisión de gestión adecuada?",
  "Automation Result": "Resultado de la automatización",
  "Guest Issue": "Problema del huésped",
  "Issue Category": "Categoría del problema",
  "Routed To": "Derivado a",
  "Human Review": "Revisión humana",
  "Status": "Estado",
  "Workflows changes could not be saved. Check browser storage or available space and try again.": "No se pudieron guardar los cambios de Flujos de trabajo. Comprueba el almacenamiento o espacio disponible e inténtalo de nuevo.",
  "Complete the step/stage, what happens, who handles it, and why.": "Completa el paso, lo que ocurre, quién lo gestiona y por qué.",
  "Workflow step saved.": "Paso del flujo guardado.",
  "Workflow sequence updated.": "Secuencia del flujo actualizada.",
  "Workflow step deleted.": "Paso del flujo eliminado.",
  "Add a workflow name, purpose, and at least one saved step before preparing an AI review prompt.": "Añade un nombre, un propósito y al menos un paso guardado antes de preparar la instrucción de revisión para IA.",
  "AI workflow review prompt prepared.": "Instrucción de revisión del flujo preparada.",
  "Paste useful AI feedback before recording it for review.": "Pega comentarios útiles de IA antes de registrarlos para revisión.",
  "Further review": "Revisión adicional",
  "AI feedback recorded temporarily for your review. It did not change the workflow.": "Comentarios de IA registrados temporalmente para revisión. No cambiaron el flujo.",
  "Record the expected workflow, run the workflow, and complete the problem/exception and manager decision.": "Registra el flujo esperado, ejecútalo y completa el problema/excepción y la decisión del gerente.",
  "Workflow Test Record saved.": "Registro de prueba del flujo guardado.",
  "Record Expected Workflow before running the workflow.": "Registra el flujo esperado antes de ejecutarlo.",
  "Select a supplied situation and configure its Route To rule before running.": "Selecciona una situación proporcionada y configura su regla de derivación antes de ejecutar.",
  "Workflow run complete. Evaluate the generated result.": "Ejecución completada. Evalúa el resultado generado.",
  "Affirm the manager responsibility acknowledgment before saving the Management Evaluation.": "Confirma la responsabilidad del gerente antes de guardar la evaluación de gestión.",
  "Complete all five Management Evaluation responses.": "Completa las cinco respuestas de evaluación de gestión.",
  "Management Evaluation saved in this browser.": "Evaluación de gestión guardada en este navegador.",
  "Undergraduate Week 5 · MAP → AUTOMATE → CONTROL → TEST": "Semana 5 de pregrado · MAPEAR → AUTOMATIZAR → CONTROLAR → PROBAR",
  "Workflows & Automation": "Flujos de trabajo y automatización",
  "Map a process, automate appropriate steps, keep human control visible, and test whether the workflow works as intended.": "Mapea un proceso, automatiza los pasos apropiados, mantén visible el control humano y comprueba si el flujo funciona como se esperaba.",
  "Review your weekly briefing, then use Test Automation to check the rule against Planner. You decide what to do next.": "Revisa el informe semanal y usa Probar automatización para comprobar la regla con el Planificador. Tú decides qué hacer después.",
  "Map the guest issue response, configure routing and human review, then run the supplied situations and evaluate the results.": "Mapea la respuesta a problemas de huéspedes, configura derivaciones y revisión humana, ejecuta las situaciones proporcionadas y evalúa los resultados.",
  "Supplied guest issue situations": "Situaciones proporcionadas de problemas de huéspedes",
  "These are the same situations available in Test Workflow. Your routing rules determine the result; written workflow steps are not executed automatically.": "Son las mismas situaciones disponibles en Probar flujo. Tus reglas de derivación determinan el resultado; los pasos escritos no se ejecutan automáticamente.",
  "Map · Control": "Mapear · Controlar",
  "Guest Issue Response Workflow": "Flujo de respuesta a problemas de huéspedes",
  "+ Add workflow step": "+ Añadir paso al flujo",
  "Workflow name": "Nombre del flujo",
  "e.g., Coastal Life Guest Issue Response": "p. ej., Respuesta a problemas de huéspedes de Coastal Life",
  "Workflow purpose": "Propósito del flujo",
  "What should this workflow accomplish?": "¿Qué debe lograr este flujo?",
  "Edit workflow step": "Editar paso del flujo",
  "Add workflow step": "Añadir paso al flujo",
  "Step / stage": "Paso / etapa",
  "Who or what handles it?": "¿Quién o qué lo gestiona?",
  "What happens": "Qué ocurre",
  "Human Review?": "¿Revisión humana?",
  "Why?": "¿Por qué?",
  "Save workflow step": "Guardar paso del flujo",
  "No workflow steps yet": "Aún no hay pasos en el flujo",
  "Add steps in the sequence you want to test. The dashboard will not decide the correct workflow for you.": "Añade los pasos en el orden que quieres probar. El panel no decidirá por ti cuál es el flujo correcto.",
  "Human review:": "Revisión humana:",
  "Why:": "Por qué:",
  "Edit step": "Editar paso",
  "Delete step": "Eliminar paso",
  "Delete this workflow step? Existing test records will remain.": "¿Eliminar este paso? Los registros de pruebas existentes permanecerán.",
  "Keep step": "Conservar paso",
  "Automate · Control": "Automatizar · Controlar",
  "Automation Rules": "Reglas de automatización",
  "Configure each category’s routing rule. Changes save in this browser immediately. Run Workflow applies these rules; it does not execute your written workflow steps. This rule-based automation does not contact employees or complete guest issues.": "Configura la regla de derivación de cada categoría. Los cambios se guardan de inmediato en este navegador. Ejecutar flujo aplica estas reglas; no ejecuta los pasos escritos. Esta automatización no contacta a empleados ni resuelve problemas de huéspedes.",
  "Route To": "Derivar a",
  "{0} Route To": "{0} — Derivar a",
  "Automation rule saved.": "Regla de automatización guardada.",
  "Select a destination": "Seleccionar destino",
  "{0} Human Review": "{0} — Revisión humana",
  "Automate · Review": "Automatizar · Revisar",
  "Prepare AI Workflow Review Prompt": "Preparar instrucción de revisión del flujo para IA",
  "Generate workflow review prompt": "Generar instrucción de revisión del flujo",
  "AI Workflow Review Prompt": "Instrucción de revisión del flujo para IA",
  "Paste AI workflow feedback": "Pegar comentarios de IA sobre el flujo",
  "Paste feedback from your approved external AI tool.": "Pega comentarios de tu herramienta de IA aprobada.",
  "Record feedback for review": "Registrar comentarios para revisión",
  "AI feedback under student review": "Comentarios de IA bajo revisión del estudiante",
  "AI suggestion · not accepted workflow": "Sugerencia de IA · flujo sin aceptar",
  "Feedback under review": "Comentarios en revisión",
  "Rejected / ignored": "Rechazado / ignorado",
  "Accepted through deliberate workflow edit": "Aceptado mediante edición deliberada del flujo",
  "To accept a suggestion, deliberately edit the saved workflow above. This feedback never changes it automatically and remains temporary.": "Para aceptar una sugerencia, edita deliberadamente el flujo guardado. Estos comentarios nunca lo cambian automáticamente y son temporales.",
  "Test": "Prueba",
  "Test Workflow": "Probar flujo",
  "+ Add Workflow Test Record": "+ Añadir registro de prueba del flujo",
  "Test all four guest issue situations by running them through your configured automation rules. You may save more than one record per situation when you revise and retest.": "Prueba las cuatro situaciones con las reglas configuradas. Puedes guardar más de un registro por situación cuando revises y repitas la prueba.",
  "test record(s)": "registro(s) de prueba",
  "Edit Workflow Test Record": "Editar registro de prueba del flujo",
  "Add Workflow Test Record": "Añadir registro de prueba del flujo",
  "Test Situation": "Situación de prueba",
  "Select a situation": "Seleccionar situación",
  "Problem/Exception?": "¿Problema/Excepción?",
  "Select what testing showed": "Seleccionar qué mostró la prueba",
  "Expected Workflow": "Flujo esperado",
  "Historical student observation:": "Observación histórica del estudiante:",
  "Run Workflow": "Ejecutar flujo",
  "Manager Decision": "Decisión del gerente",
  "Save Workflow Test Record": "Guardar registro de prueba del flujo",
  "Edit test record": "Editar registro de prueba",
  "Rerun situation": "Volver a ejecutar situación",
  "Manager judgment": "Criterio del gerente",
  "Management Evaluation": "Evaluación de gestión",
  "I reviewed the workflow design, AI feedback I chose to use, and test results. I take responsibility for this management evaluation.": "Revisé el diseño del flujo, los comentarios de IA que elegí utilizar y los resultados de las pruebas. Asumo la responsabilidad de esta evaluación de gestión.",
  "Save Management Evaluation": "Guardar evaluación de gestión",
  "Saved Management Evaluation": "Evaluación de gestión guardada",
  "Completed Management Evaluation": "Evaluación de gestión completada",
  "Edit Management Evaluation": "Editar evaluación de gestión",
  "Week 5 saved work stays in this browser on this device. AI prompt, pasted feedback, and review judgment are temporary working state.": "El trabajo guardado de la Semana 5 permanece en este navegador y dispositivo. La instrucción de IA, los comentarios pegados y el juicio de revisión son temporales.",
  "Coastal Life Management Application": "Aplicación de gestión de Coastal Life"
};
